apiVersion: v1
kind: Secret
metadata:
  name: selectgearmotors-transaction-api-secrets
  namespace: selectgearmotors-ns
type: Opaque
stringData:
  API_GATEWAY_CAR_SELLER_URL: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  API_GATEWAY_CLIENT_URL: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  API_GATEWAY_PAYMENT_URL: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  API_GATEWAY_VEHICLE_URL: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  API_PORT: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  AWS_REGION: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  AWS_SQS_QUEUE_DOCUMENT_URL: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  AWS_SQS_QUEUE_NOTIFICATION_URL: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  DATABASE_PASSWORD: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  DATABASE_URL: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  DATABASE_USERNAME: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  MAIL_HOST: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  MAIL_PASSWORD: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  MAIL_PORT: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  MAIL_USERNAME: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  SECURITY_JWT_SECRET_KEY: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  SWAGGER_API_URL: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  ZIPKIN_URL: "${{ secrets.AWS_ACCESS_KEY_ID }}"
