package br.com.selectgearmotors.transaction.application.event.dto;

public record ContactDTO(String name,
                          String phone,
                          String email,
                          String website,
                          String address,
                          String city,
                          String state,
                          String country,
                          String zipCode,
                          String image,
                          String video,
                          String date,
                          String time,
                          String location,
                          String description,
                          String category,
                          String subcategory,
                          String brand,
                          String type,
                          String price,
                          String status,
                          String fuel,
                          String km,
                          String year,
                          String chassis,
                          String renavam,
                          String color) {
}
