name: CI/CD para AWS EKS
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: rogeriofontes/selectgearmotors-transaction-api:v8

      - name: Configure kubectl
        run: |
          aws eks --region us-east-1 update-kubeconfig --name selectgearmotors-eks-cluster

      - name: Create Kubernetes Secret YAML
        run: |
          cat <<EOF > infra/k8s/secrets.yaml
          apiVersion: v1
          kind: Secret
          metadata:
            name: selectgearmotors-transaction-api-secrets
            namespace: selectgearmotors-ns
          type: Opaque
          stringData:
            API_GATEWAY_CAR_SELLER_URL: "${{ secrets.AWS_ACCESS_KEY_ID }}"
            API_GATEWAY_CLIENT_URL: "${{ secrets.AWS_ACCESS_KEY_ID }}"
            API_GATEWAY_PAYMENT_URL: "${{ secrets.AWS_ACCESS_KEY_ID }}"
            API_GATEWAY_VEHICLE_URL: "${{ secrets.AWS_ACCESS_KEY_ID }}"
            API_PORT: "${{ secrets.AWS_ACCESS_KEY_ID }}"
            AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
            AWS_REGION: "${{ secrets.AWS_ACCESS_KEY_ID }}"
            AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_ACCESS_KEY_ID }}"
            AWS_SQS_QUEUE_DOCUMENT_URL: "${{ secrets.AWS_ACCESS_KEY_ID }}"
            AWS_SQS_QUEUE_NOTIFICATION_URL: "${{ secrets.AWS_ACCESS_KEY_ID }}"
            DATABASE_PASSWORD: "${{ secrets.AWS_ACCESS_KEY_ID }}"
            DATABASE_URL: "${{ secrets.AWS_ACCESS_KEY_ID }}"
            #DATABASE_URL: "${{ secrets.AWS_ACCESS_KEY_ID }}"
            DATABASE_USERNAME: "${{ secrets.AWS_ACCESS_KEY_ID }}"
            MAIL_HOST: "${{ secrets.AWS_ACCESS_KEY_ID }}"
            MAIL_PASSWORD: "${{ secrets.AWS_ACCESS_KEY_ID }}"
            MAIL_PORT: "${{ secrets.AWS_ACCESS_KEY_ID }}"
            MAIL_USERNAME: "${{ secrets.AWS_ACCESS_KEY_ID }}"
            SECURITY_JWT_SECRET_KEY: "${{ secrets.AWS_ACCESS_KEY_ID }}"
            SWAGGER_API_URL: "${{ secrets.AWS_ACCESS_KEY_ID }}"
            ZIPKIN_URL: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          EOF

      - name: Apply ConfigMap and Secrets
        run: |
          kubectl apply -f infra/k8s/configmap.yaml
          kubectl apply -f infra/k8s/secrets.yaml

      - name: Apply Kubernetes Service
        run: |
          kubectl apply -f infra/k8s/service.yaml -n selectgearmotors-ns

      - name: Deploy API to EKS Cluster
        run: |
          kubectl apply -f infra/k8s/deployment.yaml -n selectgearmotors-ns
